kolunmi/bazaar

src/meson.build
Tried packaging this for CentOS Stream 10, which has libadwaita 1.6.6 and the Search screen fails because of:
```
(bazaar:7579): Gtk-CRITICAL **: 13:55:43.339: Error building template class 'BzS
earchWidget' for an instance of type 'BzSearchWidget': .:0:0 Invalid property: A
dwBottomSheet.reveal-bottom-bar
```
Which is a property that got added on [Libadwaita 1.7](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/property.BottomSheet.reveal-bottom-bar.html). So lets depend on 1.7+!
=> chore(libadwaita): add explicit dependency on 1.7

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This PR adds initial support to develop bazaar through a devcontainer. This allows easier contributions and dev environment from immutable distros like bluefin. 
The dockerfile is required because ubuntu 24.04 doesn't have all the required libs to build it. Hence, ubuntu 25.04 is used.
It needs more work around flatpak to either bind to the host flatpak or make flatpak work properly inside the container to allow testing. Since wayland passthrough is enabled it's possible to launch bazaar as expected through the README after building it.
=> feat: Add initial devcontainer support

build-aux/flatpak/flatpak-bwrap-wrapper.sh, build-aux/flatpak/fuse-2.9.2-closefrom.patch, build-aux/flatpak/fuse-2.9.2-namespace-conflict-fix.patch, build-aux/flatpak/fuse-disable-sys-mount-under-flatpak.patch, build-aux/flatpak/fusermount-wrapper.sh, build-aux/flatpak/io.github.kolunmi.Bazaar.Devel.json, build-aux/flatpak/polkit-autogen, build-aux/flatpak/polkit-build-Add-option-to-build-without-polkitd.patch, build-aux/flatpak/polkit-mocklib-print-indent.patch, build-aux/flatpak/python-deps.json
This is extremely experimental but it seems to kinda work, added a flatpak manifest based on [Souk's manifest](https://gitlab.gnome.org/haecker-felix/souk/-/tree/souk-next/build-aux/flatpak?ref_type=heads) the store seems to be running, but it segfaults with an error from LibGlycin
You can build this by running:
`flatpak run org.flatpak.Builder $"./build-dir" --state-dir=$"./flatpak-builder" --ccache --force-clean --install --disable-rofiles-fuse ./io.github.kolunmi.Bazaar.Devel`
IF this ends up working, itll Fix: #6
=> feat: add flatpak manifest

build-aux/rpm/bazaar.spec
We are already packaging this on [ublue-os/packages](https://github.com/ublue-os/packages) but I thought it would be best to upstream this too
You can test the build on a Fedora 42 container then installing `rpmdevtools` and `dnf-plugins-core`.
```bash
dnf builddep -y ./bazaar.spec
spectool -agR ./bazaar.spec
rpmbuild -bb ./bazaar.spec
```
=> feat: add RPM package

.devcontainer/Dockerfile
Had to add `libyaml-dev` to the dev container to get the proper dependencies.
=> Add libyaml-dev to dev container dependencies

src/bz-full-view.c
This PR uses the `%'d` specifier to automatically format numbers with appropriate separators based on user's locale settings.
=> fix: add thousands separators to download counts with locale support

src/bz-flatpak-instance.c
Fixed: https://github.com/kolunmi/bazaar/issues/181
After cleaning up, there was only one small patch
The original XB_BUILDER_COMPILE_FLAG_SINGLE_LANG flag will cause all `lang` parameters in xml to be deleted, for example
`<name xml:lang="zh_CN">GNOME 数独</name>`
I've been understanding why `as_component_get_name_table` can't get anything except lang=C :sob:
=> Fix app name in AppStream is not loaded correctly in non-English environments

po/LINGUAS, po/pt_PT.po
Portuguese (from Portugal) is my native language and since on the Linux world we usually have a notorious lack of pt_PT translators, I decided to translate Bazaar myself. First time doing this (both translating an app and doing the github PR), so I hope everything was done right. Tell me if something needs to be adjusted. I used the commands and instructions provided in TRANSLATORS.md .
Please note that some DEs or distros configure the locale code "pt" instead of pt_PT, even KDE had a bug for some time (now fixed) that you could not select Portuguese from Portugal from the language settings UI since the options were configured in the backend as "pt_BR" and "pt" (not pt_PT) and it ended up having all apps showing Brazilian translations on both options. On this PR I used pt_PT since it is …
=> added pt_PT translations

src/meson.build
This makes it so we dont need to repackage libdex for the flatpak build (org.gnome.Sdk 48 provides libdex 0.10.1)
=> libdex: bump down requirement to 0.10

po/LINGUAS, po/uk.po
Hi.
This PR does exactly what title suggests.
Note: names transliteration was ommited. I am not proficient enough at that, and it seems to be the usual case across GNOME apps anyway. Translated the app's title though, seems to be a common case too, and the change is as straightforward as it can get.
Translation tested on Bazzite, Bazaar version `0.2.3 no-git-info`.
=> New translation: Ukrainian

README.md
Blings out the README a lot, based on this: <https://github.com/mufeedali/Wordbook/blob/main/README.md?plain=1>
=> docs(readme): bling out readme

src/bz-full-view.blp, src/bz-full-view.c, src/gtk/styles.css
This PR reworks the button layout on the app listings page to reduce visual clutter. The previous design had 3 rows of pill buttons which looked awkward in my eyes.
Changes made:
- Moved the support button underneath the developer name with custom styling to make it more prominent, to be in line with the apps stated  goal of supporting app developers
- Relocated download statistics to the "App Details" section, which also now more obviously clarifies that the number shown represents downloads in the last month
- Changed the Share button to be styled flat to reduce the number of pill buttons
I would personally also suggest removing the install button when the app is already installed to reduce confusion, but I left it alone for now as there is probably a reason for it to be there.
Feel …
=> Rework button area on full view

src/bz-full-view.blp, src/bz-full-view.c, src/gtk/styles.css
This PR moves the Git Forge Star counter next to the support button and gives it a custom style.
Since giving a star is also a form of support, I think it makes sense to place it next to the support button. This change also helps reduce clutter in the main row.
=> Move forge stars next to donation button

data/dbus/io.github.kolunmi.Bazaar.SearchProvider.service.in, data/dbus/meson.build, data/io.github.kolunmi.Bazaar.desktop.in
Also mark the desktop file as dbus-activatable so
it will work be able to get launched from dbus, and
without the service already running
=> meson: Install SearchProvider service file

src/bz-full-view.blp, src/bz-installed-page.blp, src/bz-installed-page.c, src/gtk/style.css
I made some adjustments that should hopefully lead to a better UX:
- Switched to Remove and Run buttons as i believe that most people visiting this page want to probably remove some app
- Set the application ID as the tooltip for the app name and removed the unique ID tooltip, since I don’t think even most developers need to worry about that.
- Moved the support button next to the app name and gave it styling similar to what you see on the app store page.
- Hid the permissions button under the “More actions” menu, as it’s not yet implemented. ( At first I thought I needed to install Flatseal for it to work, but the code indicates it’s simply not implemented at all.)
- Removed the “No support” button, since most users will probably understand that not having a donation link doesn’t …
=> Rework the Installed page

src/bz-application.c, src/bz-state-info.c, src/bz-state-info.h, src/bz-window.blp
This PR adjusts the layout to look more polished by making several improvements: changing the loading bar height to match default Adwaita widget, removing the non functional button around the logo, and splitting the busy label into two separate labels to remove constant layout shifts during the 'Receiving entries' step.
=> UI: Rework loading

po/it.po
Update for version 0.4.8!
- Missing translations
- Bugfix
With this release, I left some probably dev strings untranslated (e.g. Bazaar Inspector, Active Curated-Configs, etc.) for a better experience and also because I'm not able to see where they are located.
Any feedback on this would be appreciated.
=> chore(po): Update for italian translation

po/POTFILES.in
Fixes `translators.sh` script erroring out due to missing files.
=> fix(po): fix POT-files generation

src/bz-app-tile.blp, src/bz-category-tile.blp, src/bz-detailed-app-tile.blp, src/bz-full-view.blp, src/bz-installed-page.blp, src/bz-transaction-view.blp, src/bz-window.blp
Adds the `icon-dropshadow` and `lowres-icon` classes to app icons for better visibility in light mode.
See:
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.3/style-classes.html#app-icons
=> (chore) Add correct icon css classes

src/bz-flatpak-entry.c, src/bz-share-dialog.blp, src/bz-share-dialog.c
This gives the dialog a more standard look and feel, and it also allows the use of activatable-widget property.
This moves the creation of the rows into code rather than a factory, since PreferenceGroups sadly can’t be created that way.
=> (UI) Make share dialog use action rows

src/bz-decorated-screenshot.c, src/bz-window.c, src/bz-window.h
Adds a function in `BzWindow` for displaying toasts on the main window, and uses it to display a 'Copied!' toast on screenshot copy. Adding the function makes it so you don't need to scour the widget tree for the toast overlay every time you need to display a toast.
=> (UI) Add toast on screenshot copy

src/bz-window.blp
Make use of the label and icon-name properties of Adw.Toggle widgets instead of replicating them via a child widget. This also fixes the visual issue where the icons were not dimmed when the toggle was disabled.
=> (Refactor) Make use of properties of Adw.Toggle

data/io.github.kolunmi.Bazaar.gschema.xml, src/bz-preferences-dialog.blp, src/bz-preferences-dialog.c, src/bz-search-widget.blp, src/bz-search-widget.c
This PR moves the search settings to the preferences menu. This provides a more standard experience than using a popover, with the added benefits of persistence and subtitles for clearer explanations.
I also reworked the preferences dialog to use `g_settings_bind`, creating a direct binding between the setting keys and the switch widgets. This simplifies the management of these settings.
Feel free to ask for changes.
=> Move search settings to preferences dialog

src/bz-app-tile.blp, src/bz-detailed-app-tile.blp, src/bz-dynamic-list-view.c, src/bz-dynamic-list-view.h, src/bz-flathub-page.blp, src/bz-flathub-page.c, src/bz-flathub-state.c
This PR aims to make Flathub views less awkward by ensuring complete rows are always displayed and adding some other minor visual tweaks:
- Added a `max-lines-per-row` parameter to `dynamic-list-view` for better layout control.
- Displaying the app of the day together with apps of the week to ensure a divisible 6 entries.
- Updated category pages to fetch 60 entries instead of 50, so the total is divisible.
- Adjusted text weight and size in app tiles for improved readability and a cleaner look.
- Updated collections to only fetch 96 instead of a 100
=> (UX) Refine the Flathub views to be denser and have less partial lines

src/bz-entry.c, src/bz-flatpak-entry.c, src/bz-full-view.blp, src/bz-full-view.c, src/bz-release.c, src/bz-release.h
This PR redesigns the version history section of the BzFullView.  
The biggest actual change is replacing the list of issues with the release description, parsed in the same way as the long description.  
Release descriptions are included more often than issue lists and are also much more user-facing.  
I also switched to a boxed list design again, which fits better with the other design elements. Unfortunately, `boxed-list` does not work with `ListView`, so we have to construct it manually in code.
I don’t think we need to hide the version history behind a dialog, since it’s already at the bottom of the scrolled window and so it doesn’t make any other parts less accessible.
=> Rework Version History

src/bz-data-graph.c, src/bz-data-graph.h, src/bz-entry.c, src/bz-stats-dialog.blp
This PR reworks the "Downloads over time" graph by changing some styling and formatting of dates. It also removes the top and bottom bounds settings and tries to find nice automatic min and max values instead.
https://github.com/user-attachments/assets/4e3d9968-4f65-44db-8c54-4fa48f9930f6
=> rework graph UX

src/bz-full-view.c
This should hopefully make life easier for people who can’t read ISO 8601 dates.
Showcase:
=> (UX) Improve date formatting in release history

.github/workflows/build-flatpak.yml, Justfile, build-aux/flatpak/io.github.kolunmi.Bazaar.json
This is currently the only major difference between the manifests and would make it easier for me to test the flatpak that CI spits out
See:
https://github.com/flathub/io.github.kolunmi.Bazaar/commit/d46c650a51f466beded821f16e5cdc7a6b287cb0
=>  fix: use hardcoded config path
