kolunmi/bazaar

build-aux/flatpak/io.github.kolunmi.bazaar.Devel.json
data/io.github.kolunmi.bazaar.desktop.in
data/io.github.kolunmi.bazaar.service.in

Signed-off-by: Tulip Blossom <tulilirockz@proton.me>

fix: desktop file not launching on the flatpak/rpm versions

---

.github/FUNDING.yml

This will make your github sponsors front and center on this github repo page. Please do this! People are going to love your app and they _want_ to donate.

feat: add FUNDING.yml for kolunmi

---

.gitignore
Justfile

Just a few helpers for building the flatpak/rpm/base stuff, I was going to make a PR for the automated workflows but I'm tired today so here is this!

feat: add justfile for building

---

data/io.github.kolunmi.bazaar.dbus.in
data/io.github.kolunmi.bazaar.service
data/io.github.kolunmi.bazaar.service.in
data/meson.build

Change to match how flatpak's other dbus services are loaded.

Combine user service and dbus

---

po/cs.po

To make it similar to the translation in other Gnome applications + fix typos.

chore(po): Minor tweaks to the Czech translation.

---

po/ru.po

I somehow got it wrong the first time

chore(po): change lines about graph bounds for ru

---

po/it.po

added support for it-IT in bazaar, my name is Pietro F. if you need this :+1:

Add Italian Translation

---

src/bz-application.c

Thanks in advance for crediting me :)

chore: add a translator credit

---

data/io.github.kolunmi.Bazaar.metainfo.xml.in

metadata: have screenshots and some descriptions

---

po/uk.po

Still unsure what would be a better workflow — to stick with per-tag updates or with whenever there are new lines in main branch.

chore(l10n): update Ukrainian translation

---

po/LINGUAS
po/ar.po
po/cs.po
po/de.po
po/es.po
po/fa_IR.po
po/fr.po
po/id.po
po/it.po
po/pl.po
po/pt_BR.po
po/pt_PT.po
po/ru.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

Reverts kolunmi/bazaar#234
changed too many files

Revert "[Update] Italian translations"

---

po/LINGUAS
po/it.po

-added some missing translations
-added "it"  to po/LINGUAS
Hope this time will go alright :)

[Update] Italian translation

---

data/io.github.kolunmi.Bazaar.metainfo.xml.in

Fixes: https://github.com/kolunmi/bazaar/issues/292

metadata: add metadata for every release after 0.3.0, before 0.4.4

---

po/uk.po

*Fancy strings. You a translator or something?*

chore(po): update Ukrainian translation

---

po/ru.po

gonna stick to this commit message from now on

chore(po): update Russian translation

---

build-aux/flatpak/io.github.kolunmi.Bazaar.json

Fixes https://github.com/kolunmi/bazaar/issues/248

Turn bazaar-launcher script into its own module

---

po/it.po

super fast update for v. 0.4.6
- missing translations 
- bugfix with obsolete strings

chore(po): Update Italian translation

---

po/uk.po

A couple oopsies, one revision, and whatever `translators.sh` decided to do.

fix(po): fix Ukrainian translation

---

po/pt_BR.po

translation:  pt-BR update

---

README.md

Let's share the love back to those who love Bazaar!

Add testimonials section to README

---

po/cs.po

Formating fixes and other improvments

Minor improvments to Czech translaction

---

src/bz-window.blp
src/bz-window.c
src/gtk/style.css

This PR tries to make the UI feel more modern by adapting a flat design for the header bars. To be able to practically achieve this in the current layout, a switch to sidebars is also necessary.
Feel free to ask for changes.

(UX) Switch side panels to sidebars and use flat header bar designs.
